services:
  app:
    container_name: highstrom-app-dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev
    volumes:
      - ./:/app
      - /app/node_modules
