services:
  app:
    container_name: highstorm-dev
    restart: unless-stopped
    image: highstorm-dev
    build:
      context: .
      target: dev
      dockerfile: Dockerfile.dev
    command: npm run dev
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    volumes:
      - /app/.next
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    ports:
      - 3001:3000
