FROM node:22-alpine AS base

FROM base AS deps

WORKDIR /app

ADD package*.json ./

RUN npm install

FROM base AS dev

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules

ADD . .

EXPOSE 3000